### ISSUE TITLE
Add custom domain support

### ISSUE THREAD

**Issue by rpxs** [Voidchan/voidchan#30]
(TODO)

**Comment by rpxs** [comment]
(TODO)

**Comment by Vetlix** [comment]
can you elaborate?

**Comment by rpxs** [comment]
Search "domain" in the Discord. 😃 👍 👍

**Comment by TheRealKizu** [comment]
> can you elaborate?

he probs meant like `voidchan.is-aweso.me`

**Comment by rpxs** [comment]
People should be able to use their own domains with Voidchan. Ittim brought this up in the Discord, I don’t want to speak for him, though, so if he would like comment on this, it’s up to him.

**Comment by rpxs** [comment]
I can give some more context. To use voidchan on a domain someone owns, you would put in `cdn.voidchan.gg` as a CNAME record. However, as of now, this does not work, as shown by Xander: 
![image](https://user-images.githubusercontent.com/66899904/106625442-e4206d80-6533-11eb-9cf9-e3850de30908.png)

**Comment by Xander1233** [comment]
> I can give some more context. To use voidchan on a domain someone owns, you would put in `cdn.voidchan.gg` as a CNAME record. However, as of now, this does not work, as shown by Xander:
> ![image](https://user-images.githubusercontent.com/66899904/106625442-e4206d80-6533-11eb-9cf9-e3850de30908.png)

Gimme me mention

**Comment by rpxs** [comment]
@Xander1233

**Comment by TheIttim** [comment]
Howdy! I just saw Fish used my name. I brought this up to Zoro that it didn't work for a while, like 1 -2 weeks.

Zoro has now mentioned getting a load balancer server that we could route through instead in order to use custom domains.

**Comment by rpxs** [comment]
true!

**Comment by Zorotic** [comment]
I am going to begin working to fix this issue. 

This may take a few days to do however.
