### ISSUE TITLE
Discord Bot - Command Addition "help"

### ISSUE THREAD

**Issue by sleepytsu** [Voidchan/voidchan#31]
All of us within your server, _VoidChan.GG_, would like a (prefix)help command. There are some users who begin to use _Voidchan_ and don't know what all you can do with it. If there was a help command, it would solve so many issues amongst old and new users of the service you have provided for us. If you want, you can have us as a community come up with the code for you to use as the help command. I'm sure you're tired of us asking and begging you for this one single command but come on _zoro-chan_, we'd all love it.

**Comment by rpxs** [comment]
Addendum: by all of us he means [undisclosed] persons. Addendum 2, Im working on this 😃 👍 👍

**Comment by tbnritzdoge** [comment]
this would be a very sex addition 🙂

**Comment by rpxs** [comment]
omg he use potty word on github pr comment banne him!1!!!!111111!!!!! :trollface: :trollface: :trollface: :

**Comment by sleepytsu** [comment]
Doge, your access for Voidchan and the official Voidchan discord is now restricted. Please do not return.

**Comment by Zorotic** [comment]
> Addendum: by all of us he means [undisclosed] persons. Addendum 2, Im working on this smiley +1 +1

This is pretty poggers.

**Comment by sleepytsu** [comment]
I do agree with Zorotic on this, the fact that one is working on a help command for the VoidChan community is pretty poggers if I do say so myself. It's an amazing feat for just one person to obtain the information acquired to do it solo, as usually it can require more than one brain. But due to rpxs's huge IQ, I'm grateful that he is working on the help command. I appraise you, @rpxs.

**Comment by rpxs** [comment]
Wait who is rpxs? 🤔 🤔 🤔 :trollface:

**Comment by tbnritzdoge** [comment]
> Doge, your access for Voidchan and the official Voidchan discord is now restricted. Please do not return.

es hora de comer?

**Comment by sleepytsu** [comment]
> > Doge, your access for Voidchan and the official Voidchan discord is now restricted. Please do not return.
> 
> es hora de comer?

yes, feed me my command

**Comment by Zorotic** [comment]
> > Doge, your access for Voidchan and the official Voidchan discord is now restricted. Please do not return.
> 
> es hora de comer?

Sí, es cariño, estamos comiendo nuggets de pollo

**Comment by rpxs** [comment]
bro does that mean chicken nuggets im in Spanish 1 I swear I didnt use google translate

**Comment by sleepytsu** [comment]
you are unsmart fish, finish the help command

**Comment by rpxs** [comment]
hahashhahahahha thats funny "show me where I asked"

**Comment by Xander1233** [comment]
@rpxs is too slow. I will do it quick.

**Comment by rpxs** [comment]
you snooze ya lose, go ahead.

**Comment by sleepytsu** [comment]
Pr merged. Help command otw boys, lets goooo.
