### ISSUE TITLE
Delete Command deletes Image from bot but not database

### ISSUE THREAD

**Issue by TheIttim** [Voidchan/voidchan#32]
Tested by Sleepy: https://cdn.voidchan.gg/u/og19uNQ.png

**Comment by sleepytsu** [comment]
Are you exposing your superior? How dare though.

**Comment by Zorotic** [comment]
I'm aware of this issue, the issue is because we never delete the image from the cache layer.

**Comment by sleepytsu** [comment]
Is there a plan to fix this issue any time soon?

**Comment by Zorotic** [comment]
Yes there is. Very soon

**Comment by sleepytsu** [comment]
Thank you <3

**Comment by Xander1233** [comment]
Isn't it deleted from the `Repository<FileEntry>` or isn't it deleted from the actual file?

**Comment by Xander1233** [comment]
i think this can be closed, right?

**Comment by sleepytsu** [comment]
Indeed, seems to no longer be an issue. Thank you and Zoro so much!

**Comment by Xander1233** [comment]
I did nothing :D I wanted to look into this rn but then Zoro said, that he already fixed it xD

**Comment by Zorotic** [comment]
The reason this was happening was due to it not being deleted from the cache.
