### ISSUE TITLE
JPEG Website

### ISSUE THREAD

**Issue by sleepytsu** [Voidchan/voidchan#45]
[JPEG](https://cdn.voidchan.gg/u/KRuUokj.jpeg) (look at the background)
[PNG](https://cdn.voidchan.gg/v/MOkHOvQ.png) (look at the background)
Another thing I noticed; the title of the page when viewing the JPEG and PNG websites are different.

**Comment by Zorotic** [comment]
These are 2 different pages. /v/ID and /u/ID therefore this isn't really an issue. As /u/ID is simply just the image. no styling or anything.
